// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk-5pbH0xnq32HCmM52JE4y2rOeLXxdeA',
    appId: '1:525291410176:web:e1e60e0ae6980ae29899e5',
    messagingSenderId: '525291410176',
    projectId: 'pdm-recibos-22103581',
    authDomain: 'pdm-recibos-22103581.firebaseapp.com',
    storageBucket: 'pdm-recibos-22103581.appspot.com',
    measurementId: 'G-Y4HDN7P3NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCMrbUa-IZjUzbbdoLH0VEdVjIKq4QBGA',
    appId: '1:525291410176:android:9b7ec7acd11f6b799899e5',
    messagingSenderId: '525291410176',
    projectId: 'pdm-recibos-22103581',
    storageBucket: 'pdm-recibos-22103581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-WAZ65onzuU7RRtlquglElNpJmHdXCs',
    appId: '1:525291410176:ios:56c42fa34579b2c49899e5',
    messagingSenderId: '525291410176',
    projectId: 'pdm-recibos-22103581',
    storageBucket: 'pdm-recibos-22103581.appspot.com',
    iosClientId: '525291410176-d1v8j6ragm9r7sqe80nh2h83op3bmn73.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetosrecibos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH-WAZ65onzuU7RRtlquglElNpJmHdXCs',
    appId: '1:525291410176:ios:56c42fa34579b2c49899e5',
    messagingSenderId: '525291410176',
    projectId: 'pdm-recibos-22103581',
    storageBucket: 'pdm-recibos-22103581.appspot.com',
    iosClientId: '525291410176-d1v8j6ragm9r7sqe80nh2h83op3bmn73.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetosrecibos',
  );
}
